baseURL = 'http://filippoguarda.com/'
copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'
languageCode = 'en-us'
title = 'Filippo Guarda'
theme = 'tale'
sectionPagesMenu = 'main'
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "writing"
    name = "Writing"
    title = "Writing"
    url = "/writing/"
    weight = 3
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        useEmbedded = 'auto'
[params.author]
  name = "Filippo Guarda"
[[params.social]]
  title = "rss"
  icon = "ti-rss"  # Use a theme icon (e.g., Themify Icons)
  link = "https://yourdomain.com/index.xml"
